# Generated by Django 3.1.6 on 2021-02-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tital',
            new_name='title',
        ),
    ]
